version: "3.9"
services:
  account-api:
    build:
      context: ./account-api
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - spring-network

  transaction-api:
    build:
      context: ./transaction-api
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - spring-network

networks:
  spring-network:
    driver: bridge
