spring:
  application:
    name: account-api
  datasource:
    url: jdbc:h2:mem:accountdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  
server:
  port: 8081

transaction:
  service:
    api: http://transaction-api:8082

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
